name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_DEV}}
          scope: TODO-vercel-org-scope
          alias-domains: |
            dev.TODO-domain.com
  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    timeout-minutes: 10
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: TODO-github-approver-usernames
          minimum-approvals: 1
          issue-title: "Deploying to prod"
          issue-body: "Please approve or deny the deployment."

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_PROD}}
          scope: TODO-vercel-org-scope
          alias-domains: |
            TODO-prod-domain.con
